version: '3.4'
services:
  rclone:
    image: makeshift27015/rclone
    restart: unless-stopped
    network_mode: "host"
    security_opt:
      - apparmor:unconfined
    devices:
      - "/dev/fuse:/dev/fuse"
    environment:
      ItemsPerUpload: 5000
      MaxGbPerUpload: 250
      CacheSizePerMountGb: 10
      MountCommands: "                               \
        --allow-other                                \
        --allow-non-empty                            \
        --umask 000                                  \
        --uid 65534                                  \
        --gid 65534                                  \
        -v                                           \
	      --timeout 1h				                         \
        --checkers 12                                \
        --buffer-size 16M                            \
        --transfers 12                               \
        --use-mmap                                   \
        --vfs-cache-mode writes                      \
        --poll-interval 10m                         \
        --attr-timeout 10m                         \
        --dir-cache-time 20s                       \
        --vfs-read-chunk-size 1M                     \
        --vfs-read-chunk-size-limit 4G               \
        --vfs-cache-poll-interval 20s                \
        --vfs-cache-max-age 1h                     \
        --vfs-cache-max-size 100G                     \
        --cache-dir=/shared/caches/rclone_vfs/       \
        --low-level-retries 3                        \
        --multi-thread-cutoff 25M                    \
        --multi-thread-streams 8                     \
        --no-update-modtime                          \
        --rc-addr=0.0.0.0:5572                       \
	      --rc-user admin \
	      --rc-pass admin \
        --rc-enable-metrics \
        --rc"
    env_file:
      - ./rclone.env
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./rclone_conf:/rclone_conf:ro
      - ./shared/:/shared/:rshared
      - ./service_accounts/:/service_accounts/:ro
    labels:
      com.centurylinklabs.watchtower.enable: false
    deploy:
      replicas: ${rclone_enabled:-1}

  nzbhydra:
    image: makeshift27015/nzbhydra2
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./runtime_conf/nzbhydra:/config
    environment:
      - TZ=Etc/UTC
    labels:
      - proxy.hosts=nzbhydra.${domain},nzbhydra.local.${domain},nzbhydra.public.${domain}
      - proxy.port=5076
    deploy:
      replicas: ${nzbhydra_enabled:-1}

  radarr:
    image: makeshift27015/radarr
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - rclone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./runtime_conf/radarr:/config
      - ./shared/:/shared:rshared
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    labels:
      - proxy.hosts=radarr.${domain},radarr.local.${domain},radarr.public.${domain}
      - proxy.port=7878
    deploy:
      replicas: ${radarr_enabled:-1}

  sonarr:
    image: makeshift27015/sonarr
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - rclone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./runtime_conf/sonarr:/config
      - ./shared/:/shared:rshared
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    labels:
      - proxy.hosts=sonarr.${domain},sonarr.local.${domain},sonarr.public.${domain}
      - proxy.port=8989
    deploy:
      replicas: ${sonarr_enabled:-1}

  sabnzbd:
    image: makeshift27015/sabnzbd
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '12'
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    depends_on:
      - rclone
    labels:
      - proxy.hosts=sabnzbd.${domain},sabnzbd.local.${domain},sabnzbd.public.${domain}
      - proxy.port=8080
    volumes:
      - ./runtime_conf/sabnzbd:/config
      - ./shared/separate/downloads/sabnzbd:/shared/merged/downloads/sabnzbd:rshared
      - ./scripts:/scripts
    restart: unless-stopped
    deploy:
      replicas: ${sabnzbd_enabled:-1}

  traktarr:
    image: makeshift27015/traktarr
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
      RUNNOW: "yes"
    depends_on:
      - radarr
      - sonarr
    volumes:
      - ./traktarr.json:/config/config.json
    restart: unless-stopped
    deploy:
      replicas: ${traktarr_enabled:-1}

  medusa:
    image: makeshift27015/medusa
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    depends_on:
      - rclone
    labels:
      - proxy.hosts=medusa.${domain},medusa.local.${domain},medusa.public.${domain}
      - proxy.port=8081
    restart: unless-stopped
    volumes:
      - ./runtime_conf/medusa:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: ${medusa_enabled:-1}

  headphones:
    image: makeshift27015/headphones
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    volumes:
      - ./runtime_conf/headphones:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - rclone
    labels:
      - proxy.hosts=headphones.${domain},headphones.local.${domain},headphones.public.${domain}
      - proxy.port=8181
    restart: unless-stopped
    deploy:
      replicas: ${headphones_enabled:-1}

  lazylibrarian:
    image: makeshift27015/lazylibrarian
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    depends_on:
      - rclone
    volumes:
      - ./runtime_conf/lazylibrarian:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro
    labels:
      - proxy.hosts=lazylibrarian.${domain},lazylibrarian.local.${domain},lazylibrarian.public.${domain}
      - proxy.port=5299
    restart: unless-stopped
    deploy:
      replicas: ${lazylibrarian_enabled:-1}

  mylar:
    image: makeshift27015/mylar
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    depends_on:
      - rclone
    volumes:
      - ./runtime_conf/mylar:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro
    labels:
      - proxy.hosts=mylar.${domain},mylar.local.${domain},mylar.public.${domain}
      - proxy.port=8090
    restart: unless-stopped
    deploy:
      replicas: ${mylar_enabled:-1}

  bazarr:
    image: makeshift27015/bazarr
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    depends_on:
      - radarr
      - sonarr
    volumes:
      - ./runtime_conf/bazarr:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro
    labels:
      - proxy.hosts=bazarr.${domain},bazarr.local.${domain},bazarr.public.${domain}
      - proxy.port=6767
    restart: unless-stopped
    deploy:
      replicas: ${bazarr_enabled:-1}

  jackett:
    image: linuxserver/jackett
    network_mode: "host"
    environment:
      TZ: "Europe/London"
    volumes:
      - ./runtime_conf/jackett:/config
    labels:
      - proxy.hosts=jackett.${domain},jackett.local.${domain},jackett.public.${domain}
      - proxy.port=9117
    restart: unless-stopped
    deploy:
      replicas: ${jackett_enabled:-1}
  
  transmission:
    image: makeshift27015/transmission
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    volumes:
      - ./runtime_conf/transmission:/config
      - ./shared/separate/downloads/transmission:/shared/merged/downloads/transmission:rshared
    labels:
      - proxy.hosts=transmission.${domain},transmission.local.${domain},transmission.public.${domain}
      - proxy.port=9091
    restart: unless-stopped
    deploy:
      replicas: ${transmission_enabled:-1}

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: --cleanup --interval 21600
    deploy:
      replicas: ${watchtower_enabled:-1}

  unmanic:
    image: makeshift27015/unmanic
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - rclone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./runtime_conf/unmanic:/config
      - ./shared/caches/unmanic:/tmp/unmanic
      - ./shared/:/shared:rshared
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK: 000
    labels:
      - proxy.hosts=unmanic.${domain},unmanic.local.${domain},unmanic.public.${domain}
      - proxy.port=8888
    deploy:
      replicas: ${unmanic_enabled:-1}
