version: '3.4'
services:
  rclone:
    image: makeshift27015/rclone
    restart: unless-stopped
    network_mode: "host"
    security_opt:
      - apparmor:unconfined
    devices:
      - "/dev/fuse:/dev/fuse"
    environment:
      ItemsPerUpload: 10
      CacheSizePerMountGb: 10
      MountCommands: "                               \
        --fast-list                                  \
        --allow-other                                \
        --allow-non-empty                            \
        --umask 000                                  \
        --uid 65534                                  \
        --gid 65534                                  \
        -v                                           \
        --checkers 12                                \
        --buffer-size 16M                            \
        --transfers 12                               \
        --use-mmap                                   \
        --vfs-cache-mode writes                      \
        --poll-interval 120s                         \
        --attr-timeout 8700h                         \
        --dir-cache-time 8760h                       \
        --vfs-read-chunk-size 1M                     \
        --vfs-read-chunk-size-limit 4G               \
        --vfs-cache-poll-interval 20m                \
        --vfs-cache-max-age 168h                     \
        --vfs-cache-max-size 50G                     \
        --cache-dir=/shared/caches/rclone_vfs/       \
        --low-level-retries 3                        \
        --multi-thread-cutoff 25M                    \
        --multi-thread-streams 8                     \
        --no-update-modtime                          \
        --rc-addr=0.0.0.0:5572                       \
        --drive-service-account-file /service_accounts/1.json \
        --rc"
    env_file:
      - ./rclone.env
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./rclone_conf:/rclone_conf:ro
      - ./shared/:/shared/:rshared
      - ./service_accounts/:/service_accounts/:ro

  nzbhydra:
    image: hotio/nzbhydra2
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./runtime_conf/nzbhydra:/config
    environment:
      - TZ=Etc/UTC
    labels:
      - proxy.hosts=nzbhydra.${domain},nzbhydra.local.${domain},nzbhydra.public.${domain}
      - proxy.port=5076

  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - rclone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./runtime_conf/radarr:/config
      - ./shared/:/shared:rshared
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK_SET: 000
    labels:
      - proxy.hosts=radarr.${domain},radarr.local.${domain},radarr.public.${domain}
      - proxy.port=7878

  sonarr:
    image: linuxserver/sonarr:preview
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - rclone
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./runtime_conf/sonarr:/config
      - ./shared/:/shared:rshared
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK_SET: 000
    labels:
      - proxy.hosts=sonarr.${domain},sonarr.local.${domain},sonarr.public.${domain}
      - proxy.port=8989

  sabnzbd:
    image: linuxserver/sabnzbd
    network_mode: "host"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '12'
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK_SET: 000
    depends_on:
      - rclone
    labels:
      - proxy.hosts=sabnzbd.${domain},sabnzbd.local.${domain},sabnzbd.public.${domain}
      - proxy.port=8080
    volumes:
      - ./runtime_conf/sabnzbd:/config
      - ./shared/separate/downloads/sabnzbd:/shared/merged/downloads/sabnzbd:rshared
      - ./scripts:/scripts
    restart: unless-stopped

  traktarr:
    image: makeshift27015/traktarr
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK_SET: 000
      RUNNOW: "yes"
    depends_on:
      - radarr
      - sonarr
    volumes:
      - ./traktarr.json:/config/config.json
    restart: unless-stopped

  medusa:
    image: linuxserver/medusa
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK_SET: 000
    depends_on:
      - rclone
    labels:
      - proxy.hosts=medusa.${domain},medusa.local.${domain},medusa.public.${domain}
      - proxy.port=8081
    restart: unless-stopped
    volumes:
      - ./runtime_conf/medusa:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro

  headphones:
    image: linuxserver/headphones
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK_SET: 000
    volumes:
      - ./runtime_conf/headphones:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - rclone
    labels:
      - proxy.hosts=headphones.${domain},headphones.local.${domain},headphones.public.${domain}
      - proxy.port=8181
    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK_SET: 000
    depends_on:
      - rclone
    volumes:
      - ./runtime_conf/lazylibrarian:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro
    labels:
      - proxy.hosts=lazylibrarian.${domain},lazylibrarian.local.${domain},lazylibrarian.public.${domain}
      - proxy.port=5299
    restart: unless-stopped

  mylar:
    image: linuxserver/mylar
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK_SET: 000
    depends_on:
      - rclone
    volumes:
      - ./runtime_conf/mylar:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro
    labels:
      - proxy.hosts=mylar.${domain},mylar.local.${domain},mylar.public.${domain}
      - proxy.port=8090
    restart: unless-stopped

  bazarr:
    image: makeshift27015/bazarr
    network_mode: "host"
    environment:
      TZ: "Europe/London"
      PUID: 65534
      PGID: 65534
      UMASK_SET: 000
    depends_on:
      - radarr
      - sonarr
    volumes:
      - ./runtime_conf/bazarr:/config
      - ./shared/:/shared:rshared
      - /etc/localtime:/etc/localtime:ro
    labels:
      - proxy.hosts=bazarr.${domain},bazarr.local.${domain},bazarr.public.${domain}
      - proxy.port=6767
    restart: unless-stopped
