version: '3.4'
services:
  rclone_plex:
    image: makeshift27015/rclone
    restart: unless-stopped
    network_mode: "host"
    security_opt:
      - apparmor:unconfined
    devices:
      - "/dev/fuse:/dev/fuse"
    env_file:
      - ./rclone.env
    environment:
        ItemsPerUpload: 16
        MountPoint: "/shared/plex"
        CacheFolderSuffix: "_plex"
        MountCommands: "                             \
        --fast-list                                  \
        --allow-other                                \
        --allow-non-empty                            \
        --umask 000                                  \
        --uid 65534                                  \
        --gid 65534                                  \
        -v                                           \
        --checkers 32                                \
        --buffer-size 256M                           \
        --transfers 16                               \
        --use-mmap                                   \
        --vfs-cache-mode writes                      \
        --poll-interval 120s                         \
        --attr-timeout 22h                           \
        --dir-cache-time 24h                         \
        --vfs-read-chunk-size 1M                     \
        --vfs-read-chunk-size-limit 4G               \
        --vfs-cache-poll-interval 20m                \
        --vfs-cache-max-age 24h                      \
        --vfs-cache-max-size 256G                    \
        --cache-dir=/shared/caches/rclone_vfs_plex/  \
        --low-level-retries 3                        \
        --multi-thread-cutoff 25M                    \
        --multi-thread-streams 8                     \
        --no-update-modtime                          \
        --rc-addr=0.0.0.0:5573                       \
        --rc-no-auth \
        --drive-service-account-file /service_accounts/rclone_mount_plex.json \
        --rc"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./rclone_conf:/rclone_conf:ro
      - ./shared_plex:/shared:rshared
      - ./service_accounts:/service_accounts:ro
    labels:
      com.centurylinklabs.watchtower.enable: false
    deploy:
      replicas: ${rclone_enabled:-1}

  plex:
    image: plexinc/pms-docker:plexpass
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    env_file:
      - ./plex.env
    labels:
      - proxy.hosts=plex.${domain},plex.local.${domain},plex.public.${domain}
      - proxy.port=32400
      - proxy.template=/plex.vhost
    volumes:
      - ./runtime_conf/plex:/config/
      - ./runtime_conf/plex/Profiles:/usr/lib/plexmediaserver/Resources/Profiles/
      - ./shared_plex:/shared:rshared
      - ./runtime_conf/plex/transcode:/transcode/
    extra_hosts:
      ${plex_domain}: 127.0.0.1
    depends_on:
      - rclone_plex
    deploy:
      replicas: ${plex_enabled:-1}
